# Generated by Django 2.0 on 2018-07-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barzakh',
            options={'ordering': ('created',)},
        ),
    ]
