# Generated by Django 2.0.5 on 2018-08-20 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20180814_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('contest_id', models.CharField(blank=True, default='', max_length=128)),
                ('join_flag', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Profile')),
            ],
        ),
        migrations.RenameModel(
            old_name='Barzakh',
            new_name='Purge',
        ),
    ]
