# Generated by Django 2.0 on 2018-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180820_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AddField(
            model_name='profile',
            name='guest',
            field=models.BooleanField(default=True),
        ),
    ]
