# Generated by Django 2.0 on 2018-08-25 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180825_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, default='', max_length=128)),
                ('grade', models.CharField(blank=True, default='', max_length=128)),
                ('level', models.IntegerField(default='')),
                ('xp', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='web.Contestant')),
                ('second_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='web.Contestant')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
