# Generated by Django 2.0 on 2018-09-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180906_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='second_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='web.Contestant'),
        ),
    ]
