# Generated by Django 2.0 on 2018-09-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180906_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='field',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='level',
        ),
    ]
