# Generated by Django 2.0 on 2018-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180908_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('pic', models.URLField()),
                ('title', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('info', models.CharField(blank=True, default='', max_length=128)),
                ('pic', models.URLField()),
                ('price', models.IntegerField()),
                ('last_price', models.IntegerField()),
            ],
        ),
    ]
