# Generated by Django 2.0 on 2018-09-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180908_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='CID',
            field=models.CharField(default=0, max_length=167),
            preserve_default=False,
        ),
    ]
