# Generated by Django 2.0 on 2018-09-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_shopitem_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='pic',
            new_name='image',
        ),
    ]
