# Generated by Django 2.0 on 2018-09-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20180911_1727'),
        ('web', '0015_contest_cid'),
    ]

    operations = [
    ]
