# Generated by Django 2.0 on 2018-09-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_merge_20180915_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='CID',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_id',
            field=models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
