# Generated by Django 2.0 on 2018-09-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_merge_20180919_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='CID',
            field=models.CharField(default=None, max_length=167),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_id',
            field=models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
