# Generated by Django 2.0 on 2018-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20180915_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(default='static/images/shop/money.jpg', upload_to='static/images/shop/'),
        ),
    ]
