# Generated by Django 2.0 on 2018-09-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20180918_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='static/images/shop/money.jpg', upload_to='static/images/shop/'),
        ),
    ]
