# Generated by Django 2.0 on 2018-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_contest_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='CID',
            field=models.CharField(max_length=167),
        ),
    ]
