# Generated by Django 2.0 on 2018-09-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20180925_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='CID',
        ),
    ]
