# Generated by Django 2.0 on 2018-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_contest_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='CID',
            field=models.CharField(default=None, max_length=167),
        ),
    ]
