# Generated by Django 2.0 on 2018-09-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_contest_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='CID',
        ),
    ]
