# Generated by Django 2.0 on 2018-09-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20180925_1510'),
        ('web', '0020_auto_20180919_0000'),
    ]

    operations = [
    ]
